---
version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: monthly
      time: "09:00"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
      time: "09:00"
